# Generated by Django 3.0.9 on 2020-09-18 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(default='HCM', max_length=100, verbose_name='Kho')),
            ],
            options={
                'verbose_name_plural': 'Kho',
            },
        ),
        migrations.CreateModel(
            name='thuonghieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(default='HATOK', max_length=100, verbose_name='Thương hiệu')),
            ],
            options={
                'verbose_name_plural': 'Thương hiệu',
            },
        ),
        migrations.CreateModel(
            name='sanpham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('masp', models.CharField(max_length=100, verbose_name='Mã sản phẩm')),
                ('donvi', models.CharField(max_length=25, verbose_name='Đơn vị')),
                ('giabanle', models.IntegerField(max_length=1500, verbose_name='Giá (đã bao gồm VAT)')),
                ('soluong', models.IntegerField(default='0', max_length=10000, verbose_name='Tồn kho')),
                ('hinh', models.ImageField(blank=True, upload_to='media/sanpham/', verbose_name='Hình ảnh')),
                ('khosp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.kho', verbose_name='Kho')),
                ('thuonghieusp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.thuonghieu', verbose_name='Thương hiệu')),
            ],
            options={
                'verbose_name_plural': 'Sản phẩm',
            },
        ),
    ]
