# Generated by Django 3.0.9 on 2020-09-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='donvi',
            field=models.CharField(choices=[('cai', 'Cái'), ('hop', 'Hộp'), ('bo', 'Bộ')], default='cai', max_length=25, verbose_name='Đơn vị'),
        ),
    ]
