# Generated by Django 3.1.1 on 2020-09-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0002_auto_20200918_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='giabanle',
            field=models.IntegerField(verbose_name='Giá (đã bao gồm VAT)'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='hinh',
            field=models.ImageField(default='media/sanpham/none-img.png', upload_to='sanpham/', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='soluong',
            field=models.IntegerField(default='0', verbose_name='Tồn kho'),
        ),
    ]
