# Generated by Django 3.1.1 on 2020-09-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0004_auto_20200919_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanpham',
            name='khosp',
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='donvi',
            field=models.CharField(choices=[('cai', 'Cái'), ('hop', 'Hộp'), ('bo', 'Bộ'), ('sanpham', 'Sản phẩm')], default='sanpham', max_length=25, verbose_name='Đơn vị'),
        ),
        migrations.DeleteModel(
            name='kho',
        ),
    ]
